FROM openjdk:17-jdk-alpine

ARG JAR_FILE=build/libs/*.jar

WORKDIR /myapp

COPY ${JAR_FILE} application.jar

EXPOSE 8080

ENTRYPOINT ["java","-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=${PROFILE}", "-jar","application.jar"]
